### ISSUE TITLE
Firebase Problem

### ISSUE THREAD

**Issue by victorfob** [hyochan/DoobooIAP#7]
There is a possible way to use the app without Firebase? and in case that's is impossible, could you guys please provide credencials to it?

**Comment by leelandclay** [comment]
I haven't gone through all of the code to see if there will be other issues, but if you go to /src/components/navigation/RootStackNavigator.tsx and delete the useEffect function as well as change the return function to look like this:
```
return (
    <NavigationContainer>
      <Stack.Navigator
        initialRouteName="Main"
        screenOptions={{
          headerStyle: {
            backgroundColor: theme.background,
          },
          headerTitleStyle: { color: theme.font },
          headerTitle: '',
          headerBackTitle: '',
        }}
      >
        <Stack.Screen name="Main" component={Main} />
        <Stack.Screen name="WebView" component={WebView} />
      </Stack.Navigator>
    </NavigationContainer>
  );
```
that will change the navigation to go directly to the Main component so you can focus on just the RNIap component.

Like I said, I didn't go through all of the code...and I didn't run this locally (not on my dev system), so you may get other errors...but it should be easy to figure out what's missing and either fake it or remove the requirement.

**Comment by hyochan** [comment]
@victorfob Thanks for the issue and the interests although this is still under development. Firebase credentials should not be exposed and hence those can be easily generated by creating your free project.

Read [how to add firebase project](https://firebase.google.com/docs/web/setup) and add find below keys and replace it in `.env` followed by `.env.sample` we've provided.

```
var firebaseConfig = {
  apiKey: "api-key",
  authDomain: "project-id.firebaseapp.com",
  databaseURL: "https://project-id.firebaseio.com",
  projectId: "project-id",
  storageBucket: "project-id.appspot.com",
  messagingSenderId: "sender-id",
  appID: "app-id",
};
```
